 platform :ios, '8.0'

target 'OCExample' do
  use_frameworks!

    #pod 'LTScrollView', '~> 0.4.2'
    
    pod 'LTScrollView', :path => '../'
    
    #pod 'LTScrollView/LTLoopsPlay', :path => '../'
    #pod 'LTScrollView/LTFollowMove', :path => '../'

    
    #本Demo中使用, LTScrollView不依赖任何第三方框架
    pod 'MJRefresh', '~> 3.1.14.1'
    
end
